import { runAgent } from './base-agent.js';
import { getCoderSystemPrompt, getCoderFixSystemPrompt } from '../prompts/coder-system.js';
import { config } from '../config.js';
import { logger } from '../utils/logger.js';
import { validateAgentResponse } from '../utils/parser.js';
import { getCodebaseContext } from '../intelligence/codebase-indexer.js';
import { getStyleContext } from '../intelligence/style-detector.js';
import { getReviewFeedbackContext } from '../intelligence/review-feedback.js';

/**
 * Build the MCP server list for the Coder agent.
 * Always includes github-mcp; adds chrome-devtools when ENABLE_BROWSER_MCP=true.
 */
function getCoderMcpServers() {
  const servers = ['github-mcp'];
  if (config.enableBrowserMcp) {
    servers.push('chrome-devtools');
  }
  return servers;
}

/**
 * Ejecuta el agente Coder para implementar una tarea.
 * Crea branch, escribe código, commitea, push, abre PR.
 *
 * @param {Object} taskSpec - Especificación de la tarea (viene del Planner)
 * @param {string} taskSpec.taskId
 * @param {string} taskSpec.title
 * @param {Object} taskSpec.userStory - { who, what, why }
 * @param {string[]} taskSpec.acceptanceCriteria
 * @param {string} taskSpec.branchName
 * @param {string} taskSpec.repoUrl
 * @param {string} [cwd] - Directorio del repositorio donde trabajar
 * @param {Object} [options] - Additional options
 * @param {string} [options.model] - Model to use (from model-selector)
 * @returns {Promise<{success: boolean, pr: Object|null, cost: number|null, duration: number, error?: string}>}
 */
export async function implementTask(taskSpec, cwd, { model, codingGuidelines, architectPlan, knowledgeContext } = {}) {
  logger.taskHeader(`CODER - Implementando: ${taskSpec.title}`);

  const systemPrompt = getCoderSystemPrompt({ enableBrowserMcp: config.enableBrowserMcp });

  // Build architect plan section — when available, skip codebase exploration.
  // If a knowledgeContext is provided, use the compact coderBrief instead of the full JSON.
  let architectSection = '';
  if (knowledgeContext?.coderBrief) {
    architectSection = `\n## Implementation Plan (generated by Architect — follow this directly, DO NOT explore the codebase)\n${knowledgeContext.coderBrief}\n`;
  } else if (architectPlan) {
    const planJson = JSON.stringify(architectPlan, null, 2);
    architectSection = `\n## Implementation Plan (generated by Architect — follow this directly, DO NOT explore the codebase)\n\`\`\`json\n${planJson}\n\`\`\`\n`;
  }

  // Build codebase context if enabled AND no architect plan is available
  let codebaseSection = '';
  if (!architectPlan && config.codebaseIndexEnabled && cwd) {
    try {
      const { summary } = getCodebaseContext(cwd);
      if (summary) {
        codebaseSection = `\n## Project structure\n${summary}\n`;
      }
    } catch (err) {
      logger.warn(`Could not generate codebase index: ${err.message}`, 'CODER');
    }
  }

  // Build style guide context if enabled
  let styleSection = '';
  if (config.styleDetectorEnabled && cwd) {
    try {
      const { summary } = getStyleContext(cwd);
      if (summary) {
        styleSection = `\n## Code style rules (MANDATORY)\n${summary}\n`;
      }
    } catch (err) {
      logger.warn(`Could not generate style guide: ${err.message}`, 'CODER');
    }
  }

  // Build review feedback context (top 5 patterns relevant to this specific task)
  let feedbackSection = '';
  try {
    const { summary } = getReviewFeedbackContext({ taskSpec });
    if (summary) {
      feedbackSection = `\n## ${summary}\n`;
    }
  } catch (err) {
    logger.warn(`Could not generate review feedback: ${err.message}`, 'CODER');
  }

  // Build coding guidelines section if provided
  let guidelinesSection = '';
  if (codingGuidelines) {
    guidelinesSection = `\n## Project Coding Guidelines (MANDATORY)\n${codingGuidelines}\n`;
  }

  // Build module lessons section if available from Knowledge Graph
  let lessonsSection = '';
  if (knowledgeContext?.moduleLessons) {
    lessonsSection = `\n## Lessons from previous tasks\n${knowledgeContext.moduleLessons}\n`;
  }

  // Build codebase learning section (incremental patterns/anti-patterns from past reviews)
  let learningSection = '';
  if (knowledgeContext?.learningContext) {
    learningSection = `\n## Codebase Learning (from past reviews)\n${knowledgeContext.learningContext}\n`;
    // Count entries for logging
    const patternCount = (knowledgeContext.learningContext.match(/^- /gm) || []).length;
    logger.info(
      `[CODER] Learning context injected: ${patternCount} entries`,
      'CODER',
    );
  }

  // Build global intelligence section (cross-project patterns and anti-patterns)
  let globalInsightsSection = '';
  if (knowledgeContext?.globalInsightsContext) {
    globalInsightsSection = `\n## Global Intelligence (cross-project patterns)\n${knowledgeContext.globalInsightsContext}\n`;
  }

  // Prompt prefix sharing: static/reusable context sections go FIRST so they can be
  // cached across consecutive invocations. Dynamic task-specific content goes at the END.
  // Note: lessonsSection is task-specific (depends on taskModule) so it goes in the dynamic part.
  const staticPrefix = [codebaseSection, styleSection, feedbackSection, guidelinesSection, learningSection, globalInsightsSection]
    .filter(Boolean)
    .join('');

  const userPrompt = `${staticPrefix}${lessonsSection}
Implementa la siguiente tarea:

## Tarea
- **ID**: ${taskSpec.taskId}
- **Título**: ${taskSpec.title}

## User Story
- **Como** ${taskSpec.userStory?.who || 'usuario'}
- **Quiero** ${taskSpec.userStory?.what || taskSpec.title}
- **Para** ${taskSpec.userStory?.why || 'mejorar la aplicación'}

## Criterios de aceptación
${(taskSpec.acceptanceCriteria || []).map((c, i) => `${i + 1}. ${c}`).join('\n')}

## Instrucciones
1. Crea la branch "${taskSpec.branchName}" desde main usando create_branch con repo "${extractOwnerRepo(taskSpec.repoUrl)}". Si la branch ya existe (error al crear), haz checkout a ella con \`git checkout ${taskSpec.branchName}\` y continúa desde el código existente.
2. Implementa el código necesario (revisa si ya hay trabajo previo en la branch y continúa desde ahí)
3. Commitea y haz push a la branch
4. Si ya existe una PR abierta para esta branch, reutilízala. Si no, abre una PR con create_pr
5. **NO MERGEES LA PR**. Solo ábrela y devuelve el resultado. El merge lo hace otro agente después del review.
${architectSection}
Devuelve el resultado como JSON con: prNumber, prUrl, branchName, filesChanged, summary.`;

  const result = await runAgent({
    name: 'CODER',
    systemPrompt,
    userPrompt,
    mcpServerNames: getCoderMcpServers(),
    cwd,
    maxTurns: 50,
    totalTimeout: 900_000, // 15 min — total limit (no idle timer, Windows buffers stdout)
    model,
  });

  if (!result.success || !result.result) {
    return {
      success: false,
      pr: null,
      cost: result.cost,
      duration: result.duration,
      error: result.error || 'El Coder no devolvió un resultado válido',
    };
  }

  const data = result.result;
  const { valid, missing } = validateAgentResponse(data, ['prNumber', 'branchName']);

  if (!valid) {
    logger.warn(`Respuesta del Coder incompleta. Faltan: ${missing.join(', ')}`, 'CODER');
    return {
      success: false,
      pr: null,
      cost: result.cost,
      duration: result.duration,
      error: `Campos faltantes: ${missing.join(', ')}`,
    };
  }

  logger.success(`PR #${data.prNumber} creada: ${data.prUrl || ''}`, 'CODER');

  return {
    success: true,
    pr: {
      prNumber: data.prNumber,
      prUrl: data.prUrl || '',
      branchName: data.branchName,
      filesChanged: data.filesChanged || [],
      summary: data.summary || '',
    },
    cost: result.cost,
    duration: result.duration,
  };
}

/**
 * Ejecuta el agente Coder para arreglar issues encontrados por el Reviewer.
 * Pushea al mismo branch, NO crea nueva PR.
 *
 * @param {Object} taskSpec - Especificación original de la tarea
 * @param {number} prNumber - Número de la PR existente
 * @param {Object} reviewFeedback - Feedback del Reviewer
 * @param {string[]} reviewFeedback.issues - Lista de issues a arreglar
 * @param {string} reviewFeedback.summary - Resumen del Reviewer
 * @param {string} [cwd] - Directorio del repositorio
 * @param {Object} [options] - Additional options
 * @param {string} [options.model] - Model to use (from model-selector)
 * @returns {Promise<{success: boolean, fix: Object|null, cost: number|null, duration: number, error?: string}>}
 */
export async function fixReviewIssues(taskSpec, prNumber, reviewFeedback, cwd, { model, codingGuidelines } = {}) {
  logger.taskHeader(`CODER - Arreglando issues de PR #${prNumber}`);

  const systemPrompt = getCoderFixSystemPrompt({ enableBrowserMcp: config.enableBrowserMcp });

  const issuesList = (reviewFeedback.issues || [])
    .map((issue, i) => `${i + 1}. ${typeof issue === 'string' ? issue : issue.description || JSON.stringify(issue)}`)
    .join('\n');

  // Diff-only context: extract file paths mentioned in issues so the Coder reads
  // only the relevant files instead of exploring the full codebase.
  const mentionedFiles = extractFilesFromIssues(reviewFeedback.issues || []);
  const diffContextSection = mentionedFiles.length > 0
    ? `\n## Files to fix (diff-only context — read ONLY these files, do NOT explore the entire codebase)\n${mentionedFiles.map(f => `- ${f}`).join('\n')}\n`
    : '';

  if (mentionedFiles.length > 0) {
    logger.info(`Diff-only context: injecting ${mentionedFiles.length} file(s) mentioned in review issues`, 'CODER');
  }

  // Build review feedback context (task-relevant patterns to watch for while fixing)
  let feedbackSection = '';
  try {
    const { summary } = getReviewFeedbackContext({ taskSpec });
    if (summary) {
      feedbackSection = `\n## ${summary}\n`;
    }
  } catch (err) {
    logger.warn(`Could not generate review feedback: ${err.message}`, 'CODER');
  }

  // Build coding guidelines section if provided
  let guidelinesSection = '';
  if (codingGuidelines) {
    guidelinesSection = `\n## Project Coding Guidelines (MANDATORY)\n${codingGuidelines}\n`;
  }

  const userPrompt = `El Reviewer ha encontrado estos problemas en la PR #${prNumber}:

## Feedback del Reviewer
${reviewFeedback.summary || 'Sin resumen'}

## Issues a resolver
${issuesList || 'Sin issues específicos'}
${diffContextSection}
## Contexto de la tarea original
- **Título**: ${taskSpec.title}
- **Branch**: ${taskSpec.branchName}
- **Repo**: ${extractOwnerRepo(taskSpec.repoUrl)}
${feedbackSection}${guidelinesSection}
## Instrucciones
1. Lee SOLO los archivos mencionados en "Files to fix" (si están listados)
2. Arregla CADA issue listado arriba
3. Commitea con mensaje descriptivo (fix: ...)
4. Haz push al branch "${taskSpec.branchName}"
5. NO crees nueva PR

Devuelve el resultado como JSON con: fixed, issuesResolved, filesChanged, summary.`;

  const result = await runAgent({
    name: 'CODER',
    systemPrompt,
    userPrompt,
    mcpServerNames: getCoderMcpServers(),
    cwd,
    maxTurns: 40,
    totalTimeout: 900_000, // 15 min — total limit (no idle timer, Windows buffers stdout)
    model,
  });

  if (!result.success || !result.result) {
    return {
      success: false,
      fix: null,
      cost: result.cost,
      duration: result.duration,
      error: result.error || 'El Coder no devolvió un resultado válido al arreglar',
    };
  }

  const data = result.result;

  if (data.fixed) {
    logger.success(`Issues arreglados y pusheados a ${taskSpec.branchName}`, 'CODER');
  } else {
    logger.warn('Algunos issues no se pudieron resolver', 'CODER');
  }

  return {
    success: !!data.fixed,
    fix: {
      fixed: data.fixed,
      issuesResolved: data.issuesResolved || [],
      issuesNotResolved: data.issuesNotResolved || [],
      filesChanged: data.filesChanged || [],
      summary: data.summary || '',
    },
    cost: result.cost,
    duration: result.duration,
  };
}

/**
 * Extrae owner/repo de una URL de GitHub.
 * "https://github.com/SergioRVDev/komodo" → "SergioRVDev/komodo"
 */
function extractOwnerRepo(repoUrl) {
  if (!repoUrl) return '';
  const match = repoUrl.match(/github\.com\/([^/]+\/[^/]+)/);
  return match ? match[1].replace(/\.git$/, '') : repoUrl;
}

/**
 * Extracts file paths mentioned in review issues for diff-only context injection.
 * Looks for common file path patterns (e.g. src/foo.js, path/to/file.ts).
 *
 * @param {Array} issues - Review issues (strings or objects with .description)
 * @returns {string[]} Unique file paths found in issue text
 */
function extractFilesFromIssues(issues) {
  const FILE_PATH_RE = /(?:^|[\s`'"(])([a-zA-Z0-9_][a-zA-Z0-9._/-]*\/[a-zA-Z0-9._/-]+\.(?:js|mjs|ts|tsx|jsx|py|go|json|css|scss|md))/g;
  const files = new Set();

  for (const issue of issues) {
    const text = typeof issue === 'string' ? issue : (issue.description || issue.file || JSON.stringify(issue));
    // Also capture direct .file references from structured issue objects
    if (issue && typeof issue === 'object' && issue.file) {
      files.add(issue.file);
    }
    let match;
    FILE_PATH_RE.lastIndex = 0;
    while ((match = FILE_PATH_RE.exec(text)) !== null) {
      files.add(match[1].trim());
    }
  }

  return [...files];
}
